# Jason Hsiao

## Research question/interestsThis dataset has the mean temperature for Kelowna on Jan.01 each year and the prediction for the future. We are looking for the connection between the impact of different amount of emmisions of CO2 (carbon dioxide) and the mean temperature.

In [1]:
import pandas as pd

In [3]:
meanTemp = pd.read_csv('../data/raw/Mean_Temperature.csv')

In [5]:
meanTemp

,DateTime,Modeled Historical,Historical Range (low),Historical Range (high),RCP 2.6 Median,RCP 2.6 Range (low),RCP 2.6 Range (high),RCP 4.5 Median,RCP 4.5 Range (low),RCP 4.5 Range (high),RCP 8.5 Median,RCP 8.5 Range (low),RCP 8.5 Range (high)
0,1950-01-01,8.57,7.63,9.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1951-01-01,8.53,7.94,9.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1952-01-01,8.33,7.37,8.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1953-01-01,8.24,7.75,9.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1954-01-01,8.20,7.63,9.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,2096-01-01,NaN,NaN,NaN,10.41,9.18,11.79,12.02,10.92,12.77,14.71,13.01,15.71
147,2097-01-01,NaN,NaN,NaN,10.75,9.71,11.70,12.02,10.28,13.27,14.80,13.34,16.25
148,2098-01-01,NaN,NaN,NaN,10.21,9.29,11.60,12.08,10.37,12.97,14.75,12.94,16.57
149,2099-01-01,NaN,NaN,NaN,10.38,9.44,11.89,12.12,10.63,13.46,14.90,12.75,16.66
150,2100-01-01,NaN,NaN,NaN,10.78,9.32,11.65,11.93,10.63,12.80,14.94,13.40,16.64